#!/usr/bin/env node
/**
 * Post-export step: scans out/ and writes a service worker with a hashed
 * precache manifest so the static build works fully offline.
 */
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const outDir = path.resolve(process.cwd(), "out");
const base = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

if (!existsSync(outDir)) {
  console.error("[sw] out/ not found — run `next build` first.");
  process.exit(1);
}

function walk(dir, rel = "") {
  const out = [];
  for (const name of readdirSync(dir)) {
    const abs = path.join(dir, name);
    const r = rel ? `${rel}/${name}` : name;
    if (statSync(abs).isDirectory()) out.push(...walk(abs, r));
    else out.push(r);
  }
  return out;
}

const files = walk(outDir).filter((f) => f !== "sw.js" && !f.endsWith(".map"));

const hash = createHash("sha256");
const entries = [];
for (const rel of files) {
  const content = readFileSync(path.join(outDir, rel));
  hash.update(rel);
  hash.update(content);

  let url;
  if (rel === "index.html") url = `${base}/`;
  else if (rel.endsWith("/index.html")) url = `${base}/${rel.slice(0, -"index.html".length)}`;
  else url = `${base}/${rel}`;
  entries.push(url);
}
const revision = hash.digest("hex").slice(0, 12);

const sw = `/* FuelOps service worker — generated by scripts/build-sw.mjs (${revision}) */
const CACHE = "fuelops-${revision}";
const BASE = ${JSON.stringify(base)};
const MANIFEST = ${JSON.stringify([...new Set(entries)].sort(), null, 0)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) =>
        Promise.all(
          MANIFEST.map((url) =>
            fetch(url, { credentials: "same-origin" })
              .then((res) => (res.ok ? cache.put(url, res) : undefined))
              .catch(() => undefined),
          ),
        ),
      )
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

/** Exact match first; fall back to ignoring ?query (RSC ?_rsc / ?id= URLs). */
async function matchCache(cache, request) {
  return (await cache.match(request)) || (await cache.match(request, { ignoreSearch: true }));
}

async function networkFirst(request) {
  const cache = await caches.open(CACHE);
  try {
    const res = await fetch(request);
    if (res && res.ok) cache.put(request, res.clone());
    return res;
  } catch {
    const cached =
      (await matchCache(cache, request)) ||
      (await cache.match(BASE + "/offline/")) ||
      (await cache.match(BASE + "/"));
    if (cached) return cached;
    return new Response("You are offline", { status: 503, headers: { "Content-Type": "text/plain" } });
  }
}

async function cacheFirst(request) {
  const cached = await matchCache(caches, request);
  if (cached) return cached;
  const res = await fetch(request);
  if (res && res.ok) {
    const cache = await caches.open(CACHE);
    cache.put(request, res.clone());
  }
  return res;
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(CACHE);
  const cached = await matchCache(cache, request);
  const network = fetch(request)
    .then((res) => {
      if (res && res.ok) cache.put(request, res.clone());
      return res;
    })
    .catch(() => undefined);
  if (cached) {
    network; // revalidate in background, ignore result
    return cached;
  }
  return (await network) || Response.error();
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirst(request));
    return;
  }
  if (url.pathname.includes("/_next/static/")) {
    event.respondWith(cacheFirst(request));
    return;
  }
  event.respondWith(staleWhileRevalidate(request));
});
`;

writeFileSync(path.join(outDir, "sw.js"), sw);
console.log(`[sw] wrote out/sw.js — ${entries.length} precached URLs, revision ${revision}`);
